name: Build Aura Installer (Windows 7)

on:
  push:
    branches: [win-7-support]
  pull_request:
    branches: [win-7-support]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build project
        run: |
          scripts\build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AuraInstaller-Py-3.8
          path: dist/AuraInstaller.exe
